### ISSUE TITLE
Encoding of schema strings in metadata API

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#191]
### Steps to Reproduce:
 1. Define a csv schema in a model repository using tracdap-runtime==0.4.9
 
  ```
  field_name, field_type, label, categorical, business_key, format_code
  total_balance, FLOAT, Total drawn balance, false, false,",|.|0|£|"
  ```

 2. Pass the csv schema as the output schema definition of a model:
```
 def define_outputs(self) -> tp.Dict[str, trac.ModelOutputSchema]:
        data_schema = trac.load_schema(schemas, "data_schema.csv")

        return {"data": trac.ModelOutputSchema(data_schema)}
```

 5. Retrieve the tag for the dataset after the model has run using the metadata API

![image](https://user-images.githubusercontent.com/80156020/197184956-37b2bf81-d9d6-4f98-bbaa-4a4d718c42e3.png)

The schema format code has changed encoding (the schema in the repos is stored as UTF-8)

### Expected Result:
The schema returns as in the csv ie. "£"

### Actual Result:
Schemas come back with Â£ for pound strings. 

### Environment:
tracdap-runtime==0.4.9
@finos/tracdap-web-api: "0.4.7"
tracdap-sandbox-0.5.0-rc.1

**Comment by martin-traverse** [comment]
After investigation I found an issue in the runtime when it serializes metadata in JSON format, which is the default. Non-ascii characters are escaped, instead of using the UTF-8 representation expected by the platform.

Fix is in the linked PR, which will be in 0.5.0 RC 2. We could also release 0.4.10 if that is helpful, to include fixes from the 0.5 RC series without the major new features (data pipeline, metadata updates etc).
