### ISSUE TITLE
0.6 API Updates - Remove unused platform APIs

### ISSUE THREAD

**Issue by martin-traverse** [finos/tracdap#292]
There are duplicate APIs available for metadata batch writes. We recently added writeBatch() in the metadata API (TracMetadataApi and TrustedMetadataApi). Before this we had several separate batch methods - createObjectBatch(), updateObjectBatch() etc. This ticket is to remove the old APIs, so we will only have one writeBatch() method which can handle all types of write operation.

The change is needed in both TracMetadataApi and TrustedMetadataApi. The service .proto files need to be modified, the the uneeded implementations and service methods can be removed.

**Comment by pszajows** [comment]
In addition to changes included in the PR #307 it is necessary to remove implementation elements related to the removed platform APIs, which were used in other contexts and as such have not been removed yet. 

The initial code elements for cleansing:

- **metadata.proto** - removal of _MetadataWriteBatchRequest_ and _MetadataWriteBatchResponse_.
- **metadata_trusted.proto**,  **MetadataApiImpl.java**, **MetadataApiValidator.java**, **TrustedMetadataApi.java** and **MetadataTrustedApiValidator.java**- change of message types in the definition of  methods (like **preallocateIdBatch**) - replacing removed _MetadataWriteBatchRequest_ and _MetadataWriteBatchResponse_ with _UniversalMetadataWriteBatchRequest_ and _UniversalMetadataWriteBatchResponse_ respectively.
- **MetadataApiImpl.java** - reimplementation of **updateTag**, **createPreallocatedObject** and **preallocateIdBatch** methods. 
- Cleansing of elements, which became unused in: **MetadataWriteService.java**, **MetadataApiValidator.java** and **MetadataApiImpl.java**.
- **MetadataWriteApiTest.java** - removal of **universalizeCreateObjectBatchRequest** and **universalizeCreateObjectBatchRequest** methods and verification of places, where they were used. 
- **JobLifecycle.java** - correction of **allocateResultIds** method, so that it does not use  _MetadataWriteBatchRequest_ class. 
- ...and possibly other elements, which need to be identified.

**Comment by martin-traverse** [comment]
This is resolved by #377
